# Netlify configuration for Neureal dApp
# This file configures the build and deployment settings

[build]
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"
  publish = "frontend/build"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  REACT_APP_API_URL = "/.netlify/functions/mock-api"
  REACT_APP_WS_URL = "wss://echo.websocket.org"
  REACT_APP_CHAIN_ID = "8453"
  REACT_APP_CHAIN_NAME = "Base"
  REACT_APP_ENABLE_ANALYTICS = "true"
  REACT_APP_ENABLE_NOTIFICATIONS = "true"
  GENERATE_SOURCEMAP = "false"
  CI = "false"

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/mock-api"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Serverless functions
[functions]
  directory = "netlify/functions"
